server:
  port: '0'

spring:
  # application 정보 설정
  application:
    name: song-server
  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
  # 컨피그 서버 설정
  cloud:
    config:
      uri: ${gateway-server}
      name: song-server
      profile: docker

# AWS EC2관련 로그 error level만 남기도록 설정
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error