server:
  port: '0'

spring:
  # application 정보 설정
  application:
    name: song-server
  # 데이터 소스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smingsming_song?useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: '1234'
  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'

# eureka 설정
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# AWS 설정
cloud:
  aws:
    s3:
      bucket: ssg-smingsming
    credentials:
      access-key: AKIAQFRCJMFUSNQSG4EG
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

# AWS EC2관련 로그 error level만 남기도록 설정
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error